### ISSUE TITLE
Support ActiveSupport Cache Store for Heroku deployments

### ISSUE THREAD

**Issue by shpupti** [spk/money-open-exchange-rates#19]
Heroku uses an [ephemeral filesystem] ( https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem).
This makes a file-based-cache rather impractical (the file will be deleted on dyno restarts and will not be shared between dynos), I think a more generic cache store such as ActiveSupport's store might be a good fit.
I'd like to get some feedback and perhaps submit a pull request for this feature.

**Comment by spk** [comment]
On the README, you have an example with memory caching:

~~~
moe.cache = Proc.new do |v|
  key = 'money:exchange_rates'
  if v
    Thread.current[key] = v
  else
    Thread.current[key]
  end
end
~~~

But Redis can be use, I think ActiveSupport's store is overkill for this gem.

**Comment by shpupti** [comment]
I somehow managed to miss this part.
Thanks!
