### ISSUE TITLE
OER_URL - support https

### ISSUE THREAD

**Issue by shpupti** [spk/money-open-exchange-rates#20]
Open exchange rates has an option to access their API via https, this is important in order to avoid MiTM attacks with 'malicious rates'.
I'd like to add a moe.secure option that will access OER via https.

**Comment by shpupti** [comment]
ping?

**Comment by spk** [comment]
Sorry @shpupti, I postpone to see what to do and forget to respond. Maybe we should only support https.

**Comment by shpupti** [comment]
@spk no problem.
HTTPS is unsupported for free-tier users so perhaps it would be better for secure to be the default option and to allow disabling it for free-tier users?

**Comment by spk** [comment]
Ok I did not know, look good.

**Comment by shpupti** [comment]
Great, I will send in a PR asap.

**Comment by spk** [comment]
Thanks !
