### ISSUE TITLE
using tr to create SECURE_OER_URL results in an invalid URL (https// instead of https://)

### ISSUE THREAD

**Issue by shpupti** [spk/money-open-exchange-rates#22]
tr replaces only up to the number of characters available in the 'from_str'.

The following code for example would result in "773" instead of the expected "777":
    "123".tr("12","777")

**Comment by spk** [comment]
Oh, did not know that sorry, I will fix it soon with more tests then.

**Comment by shpupti** [comment]
Thanks!

**Comment by spk** [comment]
released https://rubygems.org/gems/money-open-exchange-rates/versions/0.3.1
