### ISSUE TITLE
requirering money in versionfile causes bundle to fail building dependencies

### ISSUE THREAD

**Issue by SDEagle** [spk/money-open-exchange-rates#23]
When adding the money gem and money-open-exchange-rates gem at the same time to a gemfile bundler fails. That is because the money-open-exchange-rates gemspec requires the version file which in turn requires money which is not installed at this point.

**Comment by spk** [comment]
Hi, I'm using a clean Rails 4.2.3 Gemfile with

``` ruby
gem 'money'
gem 'money-open-exchange-rates', github: 'spk/money-open-exchange-rates'
```

The bundle install is not failing for me. What's your setup version to be able to reproduce the error ?

**Comment by SDEagle** [comment]
I just reproduced it with the following steps (Ruby 2.2.2, OS X).
- Make sure to use a clean/empty gemset
- Start of with a completely empty ruby project
- Add `Gemfile`
```ruby
gem 'money'
gem 'money-open-exchange-rates', github: 'spk/money-open-exchange-rates'
```
- run `gem install bundler` (installed version 1.10.6)
- run `bundle`. Gives the following output:
```
Fetching git://github.com/spk/money-open-exchange-rates.git
There was a LoadError while loading money-open-exchange-rates.gemspec: 
cannot load such file -- money from
  /<rvmpath>/gems/ruby-2.2.2@foo/bundler/gems/money-open-exchange-rates-44b22381cb1b/money-open-exchange-rates.gemspec:2:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.
```

**Comment by spk** [comment]
Thanks for the explanation, I have the same issue with a clean Gemfile.
