### ISSUE TITLE
Cross-pairs - converting from non-USD to non-USD

### ISSUE THREAD

**Issue by joekur** [spk/money-open-exchange-rates#25]
I see from the open exchange rates documentation that you are expected to always convert through USD as a base (https://openexchangerates.org/documentation#relative-to-usd). Meaning if I wanted to convert CAD to GBP, it would go CAD -> USD -> GBP. However, this currently throws an error:

```ruby
Money.new(1000, "CAD").exchange_to("GBP")
```

This is because there is no direct exchange rate between the two. Would it make sense for this gem to handle the conversion through USD?

**Comment by spk** [comment]
I think this should stay the default to stay close to `openexchagerates` and its more clear.
But I think an option to change this behaviour is acceptable.

**Comment by xsve** [comment]
@joekur I submitted a pull request that handles these conversions

**Comment by spk** [comment]
Released in [v0.6.0](https://rubygems.org/gems/money-open-exchange-rates/versions/0.6.0) thanks @xsve
