### ISSUE TITLE
Redirect forbidden...

### ISSUE THREAD

**Issue by SchlauFuchs** [spk/money-open-exchange-rates#28]
/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://openexchangerates.org/latest.json?app_id=[edited] -> https://openexchangerates.org/latest.json?app_id=[edited] (RuntimeError)
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /home/deploy/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/open-uri.rb:33:in `open'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:94:in `parse_latest'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:63:in `latest'
    from gems/open_exchange_rates-0.4.1/lib/open_exchange_rates/rates.rb:36:in `exchange_rate'

**Comment by spk** [comment]
Look like they are forcing https now, can you try to use option `moe.secure_connection = true` @SchlauFuchs ?

**Comment by SchlauFuchs** [comment]
Thanks.

**Comment by xsve** [comment]
This is actually an issue with open-uri, maybe consider including https://github.com/open-uri-redirections/open_uri_redirections to allow redirections?

**Comment by Keqi** [comment]
Hi guys, enabling `moe.secure_connection = true` does not seem to work. Do you have idea how to fix it?

@xsve If I used `open_uri_redirections`, I would need to tweak `money-open-exchange-rates` to set allow_redirections flag.

**Comment by stanley90** [comment]
I monkey patched yesterday:

```
class Money::Bank::OpenExchangeRatesBank
  protected

  def read_from_url
    raise NoAppId if app_id.nil? || app_id.empty?
    open(source_url, allow_redirections: :safe).read
  end
end
```

Today it started to fail again, this time on a https -> http redirection, so I'm changing to `allow_redirections: :all`.

**Comment by spk** [comment]
Updated api url released in [0.5.0](https://rubygems.org/gems/money-open-exchange-rates/versions/0.5.0)

**Comment by enriquesalceda** [comment]
Hi,

I updated the gem, then tried to set the secure connection to true (`moe.secure_connection = true`), but I got this error:

```
/Users/enriquesalceda/workspace/goldtrex_trading/config/initializers/money.rb:5:in `block in <top (required)>': undefined method `secure_connection=' for #<Money::Bank::OpenExchangeRatesBank:0x007f995fa68268> (NoMethodError)
```

This is my configuration

![screen shot 2016-08-18 at 2 51 39 pm](https://cloud.githubusercontent.com/assets/5007193/17762376/5e453194-6553-11e6-8a92-7c452712aff6.png)

**Comment by nikue** [comment]
Post your gemfile, Enrique. Sounds like you might still have an old version.

Nikue Gardner

**Comment by enriquesalceda** [comment]
This is the Gemfile, @nikue 

![screen shot 2016-08-18 at 2 56 11 pm](https://cloud.githubusercontent.com/assets/5007193/17762436/f8596bba-6553-11e6-8dde-356c1fb88de9.png)

**Comment by nikue** [comment]
Ok, run "bundle show money-open-exchange-rates" if it returns anything less
than 0.5.0, then run "bundle update money-open-exchange-rates". If it's
already at 0.5.0 you could try running the master branch instead:

gem 'money-open-exchange-rates', branch:'master'

and the running 'bundle update' again

On Aug 18, 2016 7:56 AM, "Enrique Salceda" <notifications@github.com> wrote:

This is the Gemfile, @nikue <https://github.com/nikue>

[image: screen shot 2016-08-18 at 2 56 11 pm]
<https://cloud.githubusercontent.com/assets/5007193/17762436/f8596bba-6553-11e6-8dde-356c1fb88de9.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/spk/money-open-exchange-rates/issues/28#issuecomment-240623980>,
or mute the thread

**Comment by nikue** [comment]
It's also possible that the new API endpoint only allows secure connections
and this feature has been removed as redundant/obsolete. I haven't been
following closely...

**Comment by enriquesalceda** [comment]
@nikue Thank you man, it's working
