### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by nikue** [spk/money-open-exchange-rates#37]
Having issues getting the cache to work with Redis. Even though I have the config (below) set to rewrite the cache once a day, it seems to be having much more frequently (30-40 times per day). I've attached a shot of my usage numbers. Redis is also connected and working normally. Any idea what's wrong?

```ruby
require 'money'
require 'money/bank/open_exchange_rates_bank'
moe = Money::Bank::OpenExchangeRatesBank.new
moe.app_id = 'blahblahblah'
moe.secure_connection = true
moe.cache = Proc.new do |v|
  key = 'money:exchange_rates'
  if v
    REDIS[key] = v
  else
    REDIS[key]
  end
end
moe.update_rates
moe.ttl_in_seconds = 86400
moe.save_rates
Money.default_bank = moe
```

![capture](https://cloud.githubusercontent.com/assets/770102/20031037/2be1bc08-a37a-11e6-9c2a-aaa8207d8252.PNG)

**Comment by spk** [comment]
Hi @nikue 
You configuration look ok, but if you are working with rails do you have a re-initializer on crontab or using something like unicorn-worker-killer ?
If not can you provide a sample with Rails and money-open-exchange-rates version to reproduce the issue ?
Thanks

**Comment by nikue** [comment]
Thanks. Before I do that, I have a quick question:

1) Is it necessary to call _update_rates_ in the initializer? Since I'm working on Heroku, where dynos are restarted several times a day, I think this is where the problem is coming from.

**Comment by spk** [comment]
Ah yes, if you are working on Heroku you maybe want to avoid the [save_rates](https://github.com/spk/money-open-exchange-rates/blob/master/lib/money/bank/open_exchange_rates_bank.rb#L141)
and move this method to a Scheduler Job ?

**Comment by nikue** [comment]
Excellent idea, thanks!
