### ISSUE TITLE
(PROPOSAL) 2-layers cache Documentation

### ISSUE THREAD

**Issue by tonidas** [spk/money-open-exchange-rates#48]
I think that the documentation should talk about the two layers of cache that the gem provides:
1. The memory cache layer
2. The custom cache layer

It's very confusing at first, because there is two TTLs, the one related to the memory cache layer (native) and the one related to the custom cache layer (optional).

I can do that if the contributors agree that this is relevant.

Cheers

**Comment by spk** [comment]
Yes sure if you think it need improvement pull request are welcome @tonidas cheers

**Comment by spk** [comment]
There is more information on the PR linked; feel free to submit a PR if its still not clear

**Comment by simshanith** [comment]
To clarify, the "custom" cache is used to cache the `HTTP` response from Open Exchange Rates. The other store is an "Exchange Rates Store" with interface defined by the `Money` gem, as mentioned in several spots in the docs.

https://github.com/RubyMoney/money#exchange-rate-stores

This distinction is important in understanding why both are necessary - they cache different things with different interfaces
