### ISSUE TITLE
Async update_rates

### ISSUE THREAD

**Issue by gnclmorais** [spk/money-open-exchange-rates#59]
Hey folks!

I found this gem recently and I’m on the process of integrating it in our product. However, I’m curious about the synchronous HTTP request that `oxr.update_rates` performs when the app is booting and there’s no cache. Could we find a better way to do it, a non-blocking way? What’s your opinion about it?

Thanks!

**Comment by spk** [comment]
hey! Its possible to update the rates in a non-blocking way with crontab or a rake task documented here https://github.com/spk/money-open-exchange-rates#refresh-rates. It should be also possible to use a sidekiq job per day with https://github.com/ondrejbartas/sidekiq-cron, hope that helps

**Comment by gnclmorais** [comment]
Hey @spk, thanks for answering!

I’ve seen that on the documentation and it is something we did implement, but it left me with one question. Does that mean that we can skip the `oxr.update_rates` step on the [usage section](https://github.com/spk/money-open-exchange-rates#usage), so we can avoid the sync update and schedule an async update with cron/sidekiq?

**Comment by spk** [comment]
Hey @gnclmorais , no problems, we cannot skip the `update_rates` step if you are not using the money storage https://github.com/RubyMoney/money#exchange-rate-stores because we need to load rates on memory on the boot of your app

**Comment by gnclmorais** [comment]
Right, as I thought. But I’m still a bit unsure about something, which is the core of my question. Will `oxr.update_rates` trigger an HTTP and, if it does, how can I make sure my app doesn’t hang up (or spends too much time) on this request? Thanks! 🙌🏻

P.S.: I’ll definitely read the code more attentively to understand this, but I think it would be of use to other people to have this conversation visible.

**Comment by spk** [comment]
Yes it could if your cache is cold or if you don't have setup one; if you are not with a memory rate store you can add it to a crontab/job. i've added more doc in the associated commit
