### ISSUE TITLE
update_rates after refresh_rates?

### ISSUE THREAD

**Issue by nitsujri** [spk/money-open-exchange-rates#61]
The documentation says to place a cron/whenever to refresh the rates which works great.

It appears I should also be calling `update_rates`? I'm not 100% sure, but it looks like `refresh_rates` only updates the cache but does not change the actual rates loaded, so only on an app restart does that in the current examples?

If this is the case, perhaps it would be helpful for the cron example to include the `update_rates`.

**Comment by spk** [comment]
Yep i've added more doc on the associated commit
