### ISSUE TITLE
SSL validation failed

### ISSUE THREAD

**Issue by silva96** [spk/money-open-exchange-rates#62]
Getting 

OpenSSL::SSL::SSLError:  SSL_connect returned=1 errno=0 state=error: certificate verify failed

When refreshing rates, it looks like the root cert is expired.

**Comment by silva96** [comment]
The problem is at their side

![image](https://user-images.githubusercontent.com/4019924/83341416-3cbaaf00-a2b1-11ea-81aa-2472b5c32efe.png)

**Comment by saich-shopmatic** [comment]
Even we are also facing same problem update rates failing due to certificate issue @silva96

**Comment by spk** [comment]
Look like its resolved on their side
