### ISSUE TITLE
Request timestamp

### ISSUE THREAD

**Issue by wagneramaral** [spk/money-open-exchange-rates#67]
Would be possible to return the timestamp from when the exchange rate is fetched?

**Comment by spk** [comment]
Yes its available via rates_timestamp https://www.rubydoc.info/gems/money-open-exchange-rates/Money%2FBank%2FOpenExchangeRatesBank:rates_timestamp

**Comment by wagneramaral** [comment]
@spk sorry about that, I'm not sure how I missed that from the docs.
