### ISSUE TITLE
Money.default_bank.app_id always initialized as nil in console

### ISSUE THREAD

**Issue by morgant** [spk/money-open-exchange-rates#68]
I'm using the [full example configuration initializer with Rails and cache](https://github.com/spk/money-open-exchange-rates#full-example-configuration-initializer-with-rails-and-cache) in my `config/initializers/money_initializer.rb`, as shown in the README. Of course, I have the [example `ExchangeRate` implementation](https://github.com/RubyMoney/money#exchange-rate-stores) (from Money's README) in `app/models/exchange_rate.rb`.

When I run `OXR_API_KEY=... rails s`, it correctly initializes `Money.default_bank` and I have confirmed that `ENV['OXR_API_KEY']` & `Money.default_bank.app_id` are correctly initialized with the value specified in the environment variable. However, when running `OXR_API_KEY=... rails c`, while `ENV['OXR_API_KEY']` is set to the value specialized in the environment variable, `Money.default_bank.app_id` is _always_ `nil`, regardless of whether the Rails server is running or not.

If I manually set `Money.default_bank.app_id` when in the Rails console, I can successfully call `Money.default_bank.update_rates`, but otherwise it fails with a `Money::Bank::NoAppId` exception.

**Comment by spk** [comment]
Strange whats your Rails version @morgant ? If you could setup a project that reproduce the problem i will try to have a look thanks

**Comment by morgant** [comment]
This turned out to be a `spring` issue. My apologies for the noise.
